version: '3.8'

services:
  couchbase:
    image: couchbase:latest
    container_name: couchbase-server
    ports:
      - "8091-8094:8091-8094"   # Web UI and other services
      - "11210:11210"           # Data service
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_CLUSTER_NAME=local-cluster
      - COUCHBASE_BUCKETS=user
      - COUCHBASE_BUCKET_RAM_QUOTA=100
    volumes:
      - couchbase_data:/opt/couchbase/var

  init-couchbase:
    image: curlimages/curl:latest
    container_name: couchbase-init
    depends_on:
      - couchbase
    entrypoint: /bin/sh
    command: -c "sleep 30 && /init.sh"
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
    volumes:
      - ./init.sh:/init.sh
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  couchbase_data:
